baseurl      = "localhost"
title        = "DevOps Birmingham"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "DevOps Meetup in Birmingham"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "DevOps Birmingham Meetup"
  keywords = "devops, birmingham, meetup"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "DevOps Birmingham"
    subtitle = "A DevOps Meetup for Birmingham"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "Meetup"
    name       = "Meetup"
    url        = "https://www.meetup.com/devops-birmingham/"
  [[menu.main]]
    identifier  = "Attend"
    name       = "Attend"
    url        = "/attend"